---
# Install or update packages

#
# Install or update packages
#
- block:  ## when: not scale_daemon_running
    - block:
        - name: upgrade | Get GPFS packages list
          set_fact:
             scale_install_all_packages: "{{ scale_install_all_packages + scale_install_license_packages }}"

        - name: upgrade | Upgrade GPFS packages (yum/dnf)
          dnf:
            name: "{{ scale_install_all_packages }}"
            state: latest
            disable_gpg_check: "{{ scale_disable_gpgcheck }}"
          register: scale_install_packageresult
          when: ansible_pkg_mgr in ['yum', 'dnf']

        - name: upgrade | Upgrade GPFS packages (dnf5)
          dnf:
            use_backend: dnf5
            name: "{{ scale_install_all_packages }}"
            state: latest
            disable_gpg_check: "{{ scale_disable_gpgcheck }}"
          register: scale_install_packageresult
          when: ansible_pkg_mgr == 'dnf5'
          ignore_errors: true
          failed_when: false

        - name: upgrade | Check if GPFS packages were updated
          set_fact:
            scale_install_updated: true
      when: ansible_pkg_mgr in ['yum', 'dnf', 'dnf5']
